# Generated by Django 4.2 on 2023-04-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_alter_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
